@SmartHomeApi_HostAddress = http://localhost:5000

### Create a new Home
POST {{SmartHomeApi_HostAddress}}/graphql/
Content-Type: application/json

{
  "query": "mutation($input: HomeTypeRequestInput!) { createHome(request: $input) }",
  "variables": {
    "input": {
      "name": "Byt 2",
      "street": "Testovací 2",
      "city": "Brno",
      "zipCode": "60200"
    }
  }
}

### Getting all Homes
POST {{SmartHomeApi_HostAddress}}/graphql/
Content-Type: application/json

{
  "query": "query { allHome { id name street city }}"
}

### Get Home by ID
POST {{SmartHomeApi_HostAddress}}/graphql
Content-Type: application/json

{
  "query": "query($id: UUID!) { homeById(id: $id) { ... on HomeTypeResponse { id name street city zipCode } ... on GetErrorResult { message code entityName } } }",
  "variables": {
    "id": "81cf53b2-4f40-48c3-9225-f3d435003a44"
  }
}

### Remove Home by Id
POST {{SmartHomeApi_HostAddress}}/graphql/
Content-Type: application/json

{
  "query": "mutation { removeHomeById(homeId: \"81cf53b2-4f40-48c3-9225-f3d435003a44\") }"
}

### Create a new Room
POST {{SmartHomeApi_HostAddress}}/graphql/
Content-Type: application/json

{
  "query": "mutation($input: RoomTypeRequestInput!) { createRoom(request: $input) { ... on CreateRoomSuccess { id } ... on GetErrorResult { message code } } }",
  "variables": {
    "input": {
      "name": "Obývací pokoj",
      "type": "LivingRoom",
      "homeId": "81cf53b2-4f40-48c3-9225-f3d435003a44"
    }
  }
}

### Get all Rooms by Home Id
POST {{SmartHomeApi_HostAddress}}/graphql/
Content-Type: application/json

{
  "query": "query($homeId: UUID!) { roomsByHomeId(homeId: $homeId) {  ... on RoomsListResponse {  rooms {  id  name  type }} ... on GetErrorResult { message code } } }",
  "variables": {
    "homeId": "81cf53b2-4f40-48c3-9225-f3d435003a44"
  }
}

### Get Room by ID
POST {{SmartHomeApi_HostAddress}}/graphql
Content-Type: application/json

{
  "query": "query($id: UUID!) { roomById(id: $id) { ... on RoomTypeResponse { id name type } ... on GetErrorResult { message code entityName } } }",
  "variables": {
    "id": "00a298f8-d702-4040-b51d-10437c355f53"
  }
}

### Remove Room by ID
POST {{SmartHomeApi_HostAddress}}/graphql
Content-Type: application/json

{
  "query": "mutation($roomId: UUID!) { removeRoomById(roomId: $roomId) }",
  "variables": {
    "roomId": "e71db8b9-4859-47b7-893d-5f62728ac1dd"
  }
}

### Create a new Device
POST {{SmartHomeApi_HostAddress}}/graphql/
Content-Type: application/json

{
  "query": "mutation($input: CreateDeviceRequestInput!) { createDevice(request: $input) { ... on CreateDeviceSuccess { id } ... on GetErrorResult { message code } } }",
  "variables": {
    "input": {
      "roomId": "00a298f8-d702-4040-b51d-10437c355f53",
      "name": "Stropní světlo",
      "model": "SL-1000",
      "manufacturer": "ACME Lighting",
      "state": "Offline"
    }
  }
}

### Get devices by Room Id
POST {{SmartHomeApi_HostAddress}}/graphql/
Content-Type: application/json

{
  "query": "query($roomId: UUID!) { devicesByRoomId(roomId: $roomId) { ... on DevicesListResponse { devices { id name model manufacturer state } } ... on GetErrorResult { message code } } }",
  "variables": {
    "roomId": "00a298f8-d702-4040-b51d-10437c355f53"
  }
}

### Get Device by ID
POST {{SmartHomeApi_HostAddress}}/graphql
Content-Type: application/json

{
  "query": "query($deviceId: UUID!) { deviceById(deviceId: $deviceId) { ... on DeviceTypeResponse { id name model manufacturer state } ... on GetErrorResult { message code entityName } } }",
  "variables": {
    "deviceId": "c80c7fc8-db93-4ce9-9f37-74375e627a95"
  }
}

### Remove Device by ID
POST {{SmartHomeApi_HostAddress}}/graphql
Content-Type: application/json

{
  "query": "mutation($deviceId: UUID!) { removeDeviceById(deviceId: $deviceId) }",
  "variables": {
    "deviceId": "2cc0abe9-dab3-4774-b7a8-9b27982ff554"
  }
}